### ISSUE TITLE
Class 'SwiftUpgrade_Upgrade_Image' not found in C:\wamp\www\override\classes\Mail.php on line 199

### ISSUE THREAD

**Issue by Fraer** [firstred/swiftupgrader#1]
Hello,

After successfull install of swift upgrader v1.0.0

Prestashop 1.6.1.4

> ( ! ) Fatal error: Class 'SwiftUpgrade_Upgrade_Image' not found in C:\wamp\www\override\classes\Mail.php on line 199
> Call Stack
> #	Time	Memory	Function	Location
> 1	0.0000	248264	{main}( )	..\index.php:0
> 2	0.2250	16231800	DispatcherCore->dispatch( )	..\index.php:28
> 3	0.2340	17065392	ControllerCore->run( )	..\Dispatcher.php:367
> 4	0.2880	22129280	PasswordControllerCore->postProcess( )	..\Controller.php:178
> 5	0.3350	23713816	Mail::Send( )	..\PasswordController.php:57

**Comment by firstred** [comment]
Too much renaming perhaps.
I don't think it should contain `Upgrade` twice. Let's see if that's the cause.

**Comment by firstred** [comment]
New release: https://github.com/firstred/swiftupgrader/releases/download/1.0.1/v1.0.1-swiftupgrader.zip
